### ISSUE TITLE
Create Form for Packages Page

### ISSUE THREAD

**Issue by fmings** [nss-evening-cohort-26/gitsub-deadly-exclusives#10]
# User Story
The user will see a form to create new package that will be added to the page

# Acceptance Criteria
When the user navigates to the page, they will see an empty form 
when they complete the form, they will be able to submit the form
Upon submitting the form, a new package will be created

# Dependencies
The data structure will need to be completed
The js file will need to be linked

# Dev Notes
N/A

**Comment by alexberka** [comment]
PR #28
