### ISSUE TITLE
Projects Page: Display

### ISSUE THREAD

**Issue by Mrthincrisp** [nss-evening-cohort-26/gitsub-deadly-exclusives#14]
# User Story

Users will see a list of all current projects, and below that will be an input field to create a new project.
sidebar, header, and footer should be displayed.

# Acceptance Criteria

The current projects section should be seperate from creating a new project. 
Current projects should have an option to delete displayed.
below current projects an option to create a new project should be visable.

# Dependecies

A display for created projects, that are able to be deleted.
A field for creating new projects, to be displayed into the current projects section

# Dev Notes

**Comment by alexberka** [comment]
PR #25
