### ISSUE TITLE
Create a Data Structure File

### ISSUE THREAD

**Issue by fmings** [nss-evening-cohort-26/gitsub-deadly-exclusives#5]
# User Story
the user will be able to see the data structure objects rendered to the DOM

# Acceptance Criteria
When the user visits any of the pages, the user will be able to see the respective objects on the page

# Dependecies 
the data structure file needs to be setup to move forward when rendering any objects to the DOM

# Dev Notes
the data structure file needs to be setup to move forward when rendering any objects to the DOM

**Comment by alexberka** [comment]
Closed with #21
